TARGET = absolute leafyear passfail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable ascii star star2 one2TenWhile one2TenDoWhile randomTwoint staticLocalVariable functionSum returnValue power 간단함수선언 dice sumArray sumMatric findMax
all : ${TARGET}

absolute : $@
leafyear : $@
passfail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@
ascii : $@
star : $@
star2 : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoint : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@
power : $@
간단함수선언 : $@
dice : $@
sumArray : $@
sumMatric : $@
findMax : $@

clean :
	rm ${TARGET}