TARGET = infinit limit celsius2fahr fahr2celsius charnumber triangle arithmetics literal genderRatio compare compare2 sizeof oddeven fourbit fourbit2
all : ${TARGET}

infinit : $@
limit : $@
celsius2fair : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
arithmetics : $@
increment.c : $@
literal : $@
genderRatio : $@
compare : $@
compare2 :$@
sizeof : $@
oddeven : $@
fourbit : $@
fourbit2 : $@

clean :
	rm ${TARGET}