TARGET = infinit limit celsius2fahr fahr2celsius charnumber triangle arithmetics literal genderRatio
all : ${TARGET}

infinit : $@
limit : $@
celsius2fair : $@
fahr2celsius : $@
charNumber : $@
triangle : $@
arithmetics : $@
increment.c : $@
literal : $@
genderRatio : $@

clean :
	rm ${TARGET}