TARGET = absolute leafyear passfail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable
all : ${TARGET}

absolute : $@
leafyear : $@
passfail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@

clean :
	rm ${TARGET}