TARGET = absolute leafyear passfail grade grade2 posZeroNeg bigLetter one2Ten one2tensum multiplyTable ascii star star2 one2TenWhile one2TenDoWhile randomTwoint
all : ${TARGET}

absolute : $@
leafyear : $@
passfail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiplyTable : $@
ascii : $@
star : $@
star2 : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoint : $@

clean :
	rm ${TARGET}